import type { Message } from './i18n.ts';
/** Existing copy can use a concise shared label in translated interfaces.
 * English remains verbatim. Never use these aliases for user-authored content. */
export const aliases: Record<string, Message> = {
  '■ STOPPED': 'Stopped', '▶ PLAYING': 'Playing', 'LOADING': 'Loading…',
  'no source': 'No source', 'not connected': 'Not connected', 'Now playing': 'Now Playing',
  '● GO LIVE': 'Go live', '● Go live': 'Go live', '⤓ Download': 'Download',
  'A man\'s voice': 'Male voice', 'A woman\'s voice': 'Female voice',
  'Catalogs on this server': 'Catalogs', 'Catalog folders': 'Catalogs',
  'Parties on this server': 'Parties', 'Servers streaming now': 'Directory',
  'Playlist (0)': 'Playlist', 'Playlist folders': 'Playlist', 'Playlist pages': 'Playlist',
  'Filter these files': 'Filter', 'Filter these entries': 'Filter',
  'Filter the entries': 'Filter', 'Filter the playlist': 'Filter',
  'Create a free account': 'Create account', 'Create one': 'Create account',
  'Create your account': 'Create account', 'New here? Create an account': 'Create account',
  'Already have an account? Sign in': 'Sign in', 'Your NixAmp account': 'Your account',
  'Your public handle': 'Handle', 'handle': 'Handle', 'password': 'Password',
  'Phone number for texts': 'Phone number', 'Back to the player': 'Back',
  'Share what is playing': 'Share', 'Share this stream': 'Share',
  'Link to this stream': 'Link', 'Copy this stream\'s URL': 'Copy link',
  'A link to play': 'Link', 'A server\'s link': 'Server', 'Close translated audio purchase': 'Close',
  'Open secure checkout ↗ (new tab)': 'Open checkout', 'Checking…': 'Loading…',
  'Browse the directory': 'Directory', 'See what is live': 'Live now',
  'Join live': 'Join', 'Raise Hand': 'Raise hand', 'Hand Raises': 'Hand raises',
  'Hide this': 'Hide', 'Log': 'Activity log', 'Status:': 'Status',
  'Nixamp player': 'Playback controls', 'Nixamp audio and video player': 'Playback controls',
  'What is being said': 'Transcript', 'The room\'s chat': 'Chat', 'Trollbox': 'Chat',
  'A line for the trollbox': 'Chat message', 'Say something to the room…': 'Chat message',
  'Send it': 'Send', 'Something to add': 'Chat message', 'What to call it': 'Catalog name',
  'call it something': 'Catalog name', 'An m3u catalog to add': 'Catalogs',
  'On this device': 'Play', 'Play on this device': 'Play', 'What this is': 'About',
  'Looking for servers…': 'Loading…', 'Finding today’s conversations…': 'Loading…',
  'Coming up': 'Upcoming', 'Listen after class': 'Replay', 'Schedule live': 'Schedule class',
  'Schedule a class': 'Schedule class', 'Plan a conversation': 'Schedule class',
  'Your classroom': 'Event', 'Join in': 'Join', 'Open a room →': 'Start a room',
  'Chat message': 'Chat message', 'Add to the conversation': 'Chat message',
  'Create live': 'Create live', 'Host stage': 'Stage', 'Your host': 'Host',
  'Class host': 'Host', 'Hand raised ✓': 'Raise hand', 'Copied ✓': 'Copied',
  'Screen share with Pairux ↗': 'Screen share', 'Upload & broadcast in Nixamp ↗': 'Upload and broadcast',
  'Open Music Folder…': 'Open folder', 'Choose a music folder': 'Open folder',
  'Main navigation': 'Panels', 'Skip to a section': 'Panels',
};
